/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as DemandasRouteImport } from './routes/demandas'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemandasIndexRouteImport } from './routes/demandas.index'
import { Route as ContatosIndexRouteImport } from './routes/contatos.index'
import { Route as DemandasNovoRouteImport } from './routes/demandas.novo'
import { Route as ContatosNovoRouteImport } from './routes/contatos.novo'
import { Route as DemandasIdEditarRouteImport } from './routes/demandas.$id.editar'
import { Route as ContatosIdEditarRouteImport } from './routes/contatos.$id.editar'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandasRoute = DemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandasIndexRoute = DemandasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemandasRoute,
} as any)
const ContatosIndexRoute = ContatosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContatosRoute,
} as any)
const DemandasNovoRoute = DemandasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => DemandasRoute,
} as any)
const ContatosNovoRoute = ContatosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ContatosRoute,
} as any)
const DemandasIdEditarRoute = DemandasIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => DemandasRoute,
} as any)
const ContatosIdEditarRoute = ContatosIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => ContatosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/contatos': typeof ContatosRouteWithChildren
  '/demandas': typeof DemandasRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/contatos/novo': typeof ContatosNovoRoute
  '/demandas/novo': typeof DemandasNovoRoute
  '/contatos/': typeof ContatosIndexRoute
  '/demandas/': typeof DemandasIndexRoute
  '/contatos/$id/editar': typeof ContatosIdEditarRoute
  '/demandas/$id/editar': typeof DemandasIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/contatos/novo': typeof ContatosNovoRoute
  '/demandas/novo': typeof DemandasNovoRoute
  '/contatos': typeof ContatosIndexRoute
  '/demandas': typeof DemandasIndexRoute
  '/contatos/$id/editar': typeof ContatosIdEditarRoute
  '/demandas/$id/editar': typeof DemandasIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/contatos': typeof ContatosRouteWithChildren
  '/demandas': typeof DemandasRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/contatos/novo': typeof ContatosNovoRoute
  '/demandas/novo': typeof DemandasNovoRoute
  '/contatos/': typeof ContatosIndexRoute
  '/demandas/': typeof DemandasIndexRoute
  '/contatos/$id/editar': typeof ContatosIdEditarRoute
  '/demandas/$id/editar': typeof DemandasIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/contatos'
    | '/demandas'
    | '/relatorios'
    | '/sitemap.xml'
    | '/status'
    | '/contatos/novo'
    | '/demandas/novo'
    | '/contatos/'
    | '/demandas/'
    | '/contatos/$id/editar'
    | '/demandas/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/relatorios'
    | '/sitemap.xml'
    | '/status'
    | '/contatos/novo'
    | '/demandas/novo'
    | '/contatos'
    | '/demandas'
    | '/contatos/$id/editar'
    | '/demandas/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/contatos'
    | '/demandas'
    | '/relatorios'
    | '/sitemap.xml'
    | '/status'
    | '/contatos/novo'
    | '/demandas/novo'
    | '/contatos/'
    | '/demandas/'
    | '/contatos/$id/editar'
    | '/demandas/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  ContatosRoute: typeof ContatosRouteWithChildren
  DemandasRoute: typeof DemandasRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandas': {
      id: '/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof DemandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandas/': {
      id: '/demandas/'
      path: '/'
      fullPath: '/demandas/'
      preLoaderRoute: typeof DemandasIndexRouteImport
      parentRoute: typeof DemandasRoute
    }
    '/contatos/': {
      id: '/contatos/'
      path: '/'
      fullPath: '/contatos/'
      preLoaderRoute: typeof ContatosIndexRouteImport
      parentRoute: typeof ContatosRoute
    }
    '/demandas/novo': {
      id: '/demandas/novo'
      path: '/novo'
      fullPath: '/demandas/novo'
      preLoaderRoute: typeof DemandasNovoRouteImport
      parentRoute: typeof DemandasRoute
    }
    '/contatos/novo': {
      id: '/contatos/novo'
      path: '/novo'
      fullPath: '/contatos/novo'
      preLoaderRoute: typeof ContatosNovoRouteImport
      parentRoute: typeof ContatosRoute
    }
    '/demandas/$id/editar': {
      id: '/demandas/$id/editar'
      path: '/$id/editar'
      fullPath: '/demandas/$id/editar'
      preLoaderRoute: typeof DemandasIdEditarRouteImport
      parentRoute: typeof DemandasRoute
    }
    '/contatos/$id/editar': {
      id: '/contatos/$id/editar'
      path: '/$id/editar'
      fullPath: '/contatos/$id/editar'
      preLoaderRoute: typeof ContatosIdEditarRouteImport
      parentRoute: typeof ContatosRoute
    }
  }
}

interface ContatosRouteChildren {
  ContatosNovoRoute: typeof ContatosNovoRoute
  ContatosIndexRoute: typeof ContatosIndexRoute
  ContatosIdEditarRoute: typeof ContatosIdEditarRoute
}

const ContatosRouteChildren: ContatosRouteChildren = {
  ContatosNovoRoute: ContatosNovoRoute,
  ContatosIndexRoute: ContatosIndexRoute,
  ContatosIdEditarRoute: ContatosIdEditarRoute,
}

const ContatosRouteWithChildren = ContatosRoute._addFileChildren(
  ContatosRouteChildren,
)

interface DemandasRouteChildren {
  DemandasNovoRoute: typeof DemandasNovoRoute
  DemandasIndexRoute: typeof DemandasIndexRoute
  DemandasIdEditarRoute: typeof DemandasIdEditarRoute
}

const DemandasRouteChildren: DemandasRouteChildren = {
  DemandasNovoRoute: DemandasNovoRoute,
  DemandasIndexRoute: DemandasIndexRoute,
  DemandasIdEditarRoute: DemandasIdEditarRoute,
}

const DemandasRouteWithChildren = DemandasRoute._addFileChildren(
  DemandasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  ContatosRoute: ContatosRouteWithChildren,
  DemandasRoute: DemandasRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
